Class {
	#name : #AlbEditorFeltPen,
	#superclass : #Object,
	#instVars : [
		'shiftSelect'
	],
	#category : #'Album-UI'
}

{ #category : #'mouse handlers' }
AlbEditorFeltPen >> doubleClickEvent: anEvent [

]

{ #category : #'mouse handlers' }
AlbEditorFeltPen >> dragEndEvent: anEvent [

	
]

{ #category : #'mouse handlers' }
AlbEditorFeltPen >> dragStartEvent: anEvent [

]

{ #category : #'mouse handlers' }
AlbEditorFeltPen >> mouseDownEvent: anEvent [
]

{ #category : #updating }
AlbEditorFeltPen >> updateFrom: anEditor [

	"after layout done text decoration. Typically sent from #onLayoutDone"
]
