Class {
	#name : #AlbEditorFeltPen,
	#superclass : #Object,
	#category : #'Album-UI'
}

{ #category : #'mouse handlers' }
AlbEditorFeltPen >> doubleClickEvent: anEvent [

]

{ #category : #'mouse handlers' }
AlbEditorFeltPen >> dragEndEvent: anEvent [

	
]

{ #category : #'mouse handlers' }
AlbEditorFeltPen >> dragEvent: anEvent [

	
]

{ #category : #'mouse handlers' }
AlbEditorFeltPen >> dragStartEvent: anEvent [

]

{ #category : #'mouse handlers' }
AlbEditorFeltPen >> mouseDownEvent: anEvent [
]

{ #category : #updating }
AlbEditorFeltPen >> onLayoutDoneIn: anEditor [ 

	"after scroll done text decoration."
]

{ #category : #updating }
AlbEditorFeltPen >> onScrollDoneIn: anEditor [ 

	"after scroll done text decoration."
]
