"
!Adornments

The editor supports ''adornment'' attributes that visually influence the content of the editor. ${class:AlbTextAdornmentAttribute}$ is the superclass of all adornment attributes.

Adornment attribute can replace a piece of text with arbitrary visual elements or simply append them after a piece of text. Therefore we define two groups of adornments:

# replacing ${class:AlbTextEditorReplacingAdornmentsExamples}$
# appending ${class:AlbTextEditorAppendingAdornmentsExamples}$
"
Class {
	#name : #AlbTextEditorAdornmentsExamples,
	#superclass : #Object,
	#category : #'Album-Examples-! Documentation'
}
